EShop.MVC/Areas/Admin/Models/ProductAdmin/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EShop.MVC.Areas.Admin.Models.ProductAdmin
{
    /// <summary>
    /// View model de deicion de producto
    /// </summary>
    public class ProductViewModel
    {
        /// <summary>
        /// Identificador del producto
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Nombre del producto
        /// </summary>
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El nombre es requerido")]
        [MinLength(3, ErrorMessage ="El nombre ha de tener minimo 3 caracteres")]
        public string Name { get; set; }

        /// <summary>
        /// Descripcion corta
        /// </summary>
        [Display(Name = "Descripcion corta")]
        public string ShortDescription { get; set; }

        /// <summary>
        /// Descripcion del producto
        /// </summary>
        [Display(Name = "Descripcion")]
        public string Description { get; set; }

        /// <summary>
        /// Precio del producto
        /// </summary>
        [Display(Name = "Precio")]
        [Required(ErrorMessage = "El precio es requerido")]
        [Range(0,int.MaxValue)]
        public decimal Pice { get; set; }

        /// <summary>
        /// Stock del producto
        /// </summary>
        [Display(Name = "Stock")]
        [Required(ErrorMessage = "El precio es requerido")]
        [Range(0,int.MaxValue)]
        public decimal Stock { get; set; }

        /// <summary>
        /// Disponible o no
        /// </summary>
        [Display(Name = "Disponible")]
        public bool Available { get; set; }

        /// <summary>
        /// Iva del producto
        /// </summary>
        [Display(Name = "Iva")]
        [Required(ErrorMessage = "El Iva es requerido")]
        public int Tax_Id { get; set; }

        /// <summary>
        /// Lista de ivas
        /// </summary>
        public List<SelectListItem> Taxs { get; set; }

        /// <summary>
        /// Esta en oferta
        /// </summary>
        [Display(Name = "En oferta")]
        public bool Featured { get; set; }

        /// <summary>
        /// Descuento del producto
        /// </summary>
        [Display(Name = "Descuento")]
        public decimal? Discount { get; set; }

        public List<SelectListItem> Categories { get; set; }
        [Display(Name = "Categories")]
        public List<string> SelectedCategories { get; set; }
    }
}

EShop.MVC/Models/Product/ProductDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShop.MVC.Models.Product

    /// <sumary>
    /// Modelo de vista detalle del producto
    /// </summary>
{
    public class ProductDetailViewModel
    {
        /// <summary>
        /// ID del producto
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Id del nombre
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Imagen del producto
        /// </summary>
        public string Image { get; set; }

        /// <summary>
        /// Precio final del producto
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Precio sin desuento
        /// </summary>
        public decimal? OldPrice { get; set; }

        /// <summary>
        /// Si esta de oferta
        /// </summary>
        public bool Featured { get; set; }

        /// <summary>
        /// Descripcion del producto
        /// </summary>
        public string Description { get; set; }

    }
}

EShop.MVC/Models/Product/ProductViewModel.cs
using EShop.DTOs;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EShop.MVC.Models.Product
{
    /// <summary>
    /// View model de product Index
    /// </summary>
    public class ProductIndexViewModel
    {
        /// <summary>
        /// Coleccion de productos
        /// </summary>
        public IEnumerable<ProductDTO> Products { get; set; }

        /// <summary>
        /// Coleccion de categorias
        /// </summary>
        public IEnumerable<CategoryDTO> Categories { get; set; }

        /// <summary>
        /// Numero total de productos a mostrar
        /// </summary>
        public int ProductCount { get; set; }


    }
}

EShop.MVC/Controllers/ProductController.cs
using AutoMapper.QueryableExtensions;
using EShop.DTOs;
using EShop.MVC.Constants;
using EShop.MVC.Models.Product;
using EShop.MVC.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EShop.MVC.Controllers
{
    /// <summary>
    /// Controlador de productos
    /// </summary>
    public class ProductController : BaseController
    {
        // GET: Product
        public ActionResult Index(string orderby, string orderdir, int? take, int? skip)
        {
            var model = new ProductIndexViewModel();
            var products= Connect.Get<Tuple<int, IEnumerable<ProductDTO>>>(
                String.Format(ApiEndPoints.GetProducts, orderby, orderdir, take, skip)
                );
            var categories = Connect.Get<IEnumerable<CategoryDTO>>(
                ApiEndPoints.GetCategoryes);

            model.Products = products.Item2;
            model.ProductCount = products.Item1;
            model.Categories = categories;
            return View(model);
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            var productDetails = Connect.Get<List<ProductDTO>>(
                string.Format(ApiEndPoints.GetProduct, id))
                .AsQueryable().ProjectTo<ProductDetailViewModel>();
           // return Json(productDetails, JsonRequestBehavior.AllowGet);
           return View(productDetails);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EShop.MVC/Views/Product/Index.cshtml
@using EShop.MVC.Models.Product

@model ProductIndexViewModel

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-2">
        @Html.Partial("_Categories", Model.Categories)
    </div>
    <div class="col-md-10">
        @Html.Partial("_Products", Model.Products)
    </div>
</div>

EShop.MVC/Views/Product/ProductDetail.cshtml
@using EShop.DTOs
@model ProductDTO

<div>
    <h4>ProductDetailViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OldPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OldPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Featured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Featured)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EShop.MVC/Views/Product/_Categories.cshtml
@using EShop.DTOs
@model  IEnumerable<CategoryDTO>

<div class="column" style="margin-top:10px">
    <ul class="list-group">
        @foreach(var category in Model)
        {
            <li class="list-group-item list-group-item-action">@category.Name</li>
        }
    </ul>
</div>

EShop.MVC/Views/Product/_Product.cshtml
@using EShop.DTOs

@model ProductDTO

<div class="thumbnail" style="width: 300px; margin-top: 20px; margin-right:20px">

    <img class="card-img-top Image_@Model.Id" style="max-height:250px; max-width:200px"src="@Model.Image" alt="Product Image" />
    <div class="card-body">
        <h5 class="card-title text-center"><b>@Model.Name</b></h5>
        <p class="card-text text-center alert alert-success">@String.Format("{0:C}", Model.Price)</p>
        <div class="text-center">
            <a href="#" data-id="@Model.Id" class="btn btn-info add-to-cart">Al carrito</a>
            <a href="@Url.Action("ProductDetail", "Product", new { id=Model.Id })" class="btn btn-default"> + Info</a>
   
        </div>
    </div>
</div>

EShop.MVC/Views/Product/_Products.cshtml
@using EShop.DTOs
@model IEnumerable<ProductDTO>

<div class="productline">
    @foreach(var product in Model)
    {
        @Html.Partial("_Product", product)
    }
</div>